# Generated by Django 5.1.1 on 2024-09-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block_UTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_UTP', models.CharField(max_length=200, verbose_name='текст 1')),
                ('UTP', models.CharField(max_length=400, verbose_name='УТП')),
                ('text_button', models.CharField(max_length=100, verbose_name='Текст кнопки')),
                ('text_near_button', models.CharField(max_length=200, verbose_name='Текст возле кнопки')),
                ('image', models.ImageField(upload_to='static/images', verbose_name='Изображение УТП')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название компании')),
                ('logo', models.ImageField(upload_to='static/images', verbose_name='Логотип')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('link', models.URLField(verbose_name='Ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назнавание')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('keywords', models.CharField(max_length=200, verbose_name='Ключевые слова')),
            ],
        ),
    ]
