# Generated by Django 5.1.1 on 2024-09-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_example'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='example',
            name='example',
        ),
        migrations.AddField(
            model_name='example',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='example',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
