# Generated by Django 5.1.1 on 2024-09-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_example_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='image',
        ),
        migrations.AddField(
            model_name='example',
            name='images',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
