# Generated by Django 5.1.1 on 2024-09-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_remove_example_image_example_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example',
            old_name='images',
            new_name='image',
        ),
    ]
