# Generated by Django 5.1.1 on 2024-09-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_rename_images_example_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='sro',
            field=models.ImageField(default=1, upload_to='media/images/SRO'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='example',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
