# Generated by Django 5.1.1 on 2024-09-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_alter_example_image_alter_example_sro'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sro', models.ImageField(blank=True, null=True, upload_to='media/images/SRO')),
            ],
        ),
        migrations.RemoveField(
            model_name='example',
            name='sro',
        ),
    ]
